### ISSUE TITLE
Mind clarifying Linux installation?

### ISSUE THREAD

**Issue by trivett** [doctormo/GimpPs#13]
Having trouble getting this in. Ran the script and started Gimp again but the only evidence of it is `psicons` as a theme option. If I am missing something maybe others are as well?

**Comment by doctormo** [comment]
Would you like to improve the documentation if you got stuck?

**Comment by trivett** [comment]
Was my mistake actually. I could be wrong but I think that when I installed on Mac it put me in single window mode right away. I must have just associated that with this [awesome] setup and when it didn't happen I thought I didn't install correctly.

Thanks for the great project!
