### ISSUE TITLE
maximize button is gone

### ISSUE THREAD

**Issue by duck7000** [doctormo/GimpPs#17]
Hi there

First of all a big thank you for your work!

But i have 2 issues:
1e On Manjaro 17 (arch linux based) with the default installed gimp (2.8.22) there is no maximize button.
2e  when i press help about the screen goes from maximize to a smaller size and obviously can go back to full screen hence the missing button.

On my other pc running linuxmint 18.3 with gimp 2.8.16 there is no problem at all.

Can you look in to this?

**Comment by doctormo** [comment]
It might not be possible for me to look into it. I have Ubuntu machines, I would need a kind soul who has Arch to play with it to figure it out. Maybe it's something in the Ubuntu based config for the buttons?

**Comment by duck7000** [comment]
Ok i understand.

Can i help you? i have a spare machine where i currently test manjaro, although my Linux knowledge is limited

**Comment by duck7000** [comment]
Does it work correctly with gimp 2.8.22 on a Ubuntu machine?

**Comment by doctormo** [comment]
I don't know yet, Ubuntu 16.04 has Gimp 2.8.16 so far.

The best method to figure it out is to have the default .gimp dir and the ps gimp dir side by side and slowly copy each file other one at a time and reload gimp. When the max button disapears make a note of the file and report here attaching both versions of the files.

**Comment by duck7000** [comment]
jep on linuxmint  i also have 2.8.16, witch works fine with your theme.

Oke i will try to find witch file is causing it and get back to you asap

**Comment by duck7000** [comment]
a little update:
Only in single window mode the maximize button disapeers, in multi window mode it reapeers

**Comment by duck7000** [comment]
Sorry but i think i found the problem..

It turns out to be the screen resolution. i use a old monitor with a 1680x1050 resolution.
If i resize the left toolbar (make it wider) the maximize button reapeers in single window mode

So this issue can be closed i guess
Sorry for the inconvenience

**Comment by doctormo** [comment]
This is good to know. Maybe an upstream bug. Or do you think it's just removing the maximise button because it thinks you don't need it?

**Comment by duck7000** [comment]
I'm not sure but it looks like the program window is resized at the point of the max button (i don't know how to describe it better)
Apparently this resolution is odd and the theme can't handle it very well

**Comment by ssepan2** [comment]
Linux Mint 19.3 Cinnamon, Cinnamon 4.4.8, (Ubuntu 18.04 LTS), 1920x1080, GIMP 2.8.22

still have problem maximized, can't see bottom of app window, can't un-maximize or resize smaller.

![Screenshot from 2020-02-05 10-04-41](https://user-images.githubusercontent.com/7924858/73853538-0c7d6b00-47ff-11ea-9645-1c3b7d874a7c.png)

**Comment by duck7000** [comment]
@ssepan2 
If you resize the left toolbar it worked in my setup, just put your mouse on the edge, click left hold and move the mouse to the right and then to the left to make it as small as possible

**Comment by ssepan2** [comment]
Brilliant -- resizing that left toolbar worked like a charm to make the button re-appear and also make the windows re-sizable! :-D
Your guess is correct; this is a Windows XP theme in Cinnamon. There might be a quirk in the GTK 3 styles that causes this, but the work-around is good for now.
Thanks again, @duck7000!
Steve
