### ISSUE TITLE
spacebar+drag

### ISSUE THREAD

**Issue by chovy** [doctormo/GimpPs#7]
when I do spacebar+drag I have a weird experience because moving the mouse also moves the canvas.

not a big deal but is possible to disable the mouse moving the canvas?

**Comment by doctormo** [comment]
Yes. In the gimp go to `Edit` > `Preferences` > `Image Windows` > `Space Bar` > `While space bar is pressed` change from `Pan view` to `Do nothing`

**Comment by chovy** [comment]
can you make the plugin do that by default?

**Comment by doctormo** [comment]
I could, but I'd need more people to tell me it's a problem. Otherwise I'd certainly be disabling something without knowing who it might effect.

So you know how photoshop does panning?

**Comment by chovy** [comment]
Last time I used Ps you space+scroll. Gimp does it onMouseMove.
